workflows:
  react-native-workflow:
    name: React Native Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: npm ci --legacy-peer-deps
      - name: Build web assets
        script: npm run build
    artifacts:
      - dist/**
