default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :build_and_upload do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "../../fastlane/AuthKey.p8",
      in_house: false
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "App.xcodeproj",
      team_id: ENV["DEVELOPER_TEAM_ID"],
      bundle_identifier: "com.mashrok.ios"
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "App.xcodeproj"
    )

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.mashrok.ios" => "match AppStore com.mashrok.ios"
        }
      },
      clean: true,
      output_directory: "./build",
      output_name: "App.ipa"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
